exports.AUTHORISATION_TOKEN_STORAGE_KEY = 'accesstoken'
exports.AUTHORISATION_USER_NAME_STORAGE_KEY = 'userinfo';
exports.AUTHORISATION_USER_NAME_ZH_STORAGE_KEY = 'userinfoZh';
exports.AUTHORISATION_USER_ID_STORAGE_KEY = 'userId';
exports.AUTHORISATION_USER_HEAD_IMAGE_KEY = 'headImg';