exports.libraries = {
    "room": [
      { "name": "Color_Rainbow", "enabled": true },
      { "name": "Country_Egypt", "enabled": true },
      { "name": "Country_France", "enabled": true },
      { "name": "Country_Japan", "enabled": true },
      { "name": "Festival_Christmas", "enabled": true },
      { "name": "Festival_Halloween", "enabled": true },
      { "name": "Hobbies_Cooking", "enabled": true },
      { "name": "Hobbies_FootBall", "enabled": true },
      { "name": "Hobbies_Gaming", "enabled": true },
      { "name": "Hobbies_Garden", "enabled": true },
      { "name": "Hobbies_Sport", "enabled": true },
      { "name": "Name_Venus", "enabled": true },
      { "name": "Name_VenusB", "enabled": true },
      { "name": "Seasons_Summer", "enabled": true },
      { "name": "Shop_Bakery", "enabled": true },
      { "name": "Theme_Band", "enabled": true },
      { "name": "Theme_Magic", "enabled": true },
      { "name": "Theme_Nautical", "enabled": true },
      { "name": "Theme_Party", "enabled": true },
      { "name": "Theme_SciFi", "enabled": true },
      { "name": "Theme_StarWar", "enabled": true },
      { "name": "Theme_Wedding", "enabled": true }
    ],
    "object": [
      { "name": "Chair_Karlstad_(Color_Rainbow)", "enabled": true, "category": ["Color_Rainbow"] },
      { "name": "Rainbow_Arch_(Color_Rainbow)", "enabled": true, "category": ["Color_Rainbow"] },
      { "name": "Stacking_Tower_Toy_(Color_Rainbow)", "enabled": true, "category": ["Color_Rainbow"] },
      { "name": "Toy_Blocks_(Color_Rainbow)", "enabled": true, "category": ["Color_Rainbow"] },
      { "name": "Wall_(Color_Rainbow)", "enabled": true, "category": ["Color_Rainbow"] },
  
      { "name": "Altar_(Country_Egypt)", "enabled": true, "category": ["Country_Egypt"] },
      { "name": "Arubis_(Country_Egypt)", "enabled": true, "category": ["Country_Egypt"] },
      { "name": "Bunker_(Country_Egypt)", "enabled": true, "category": ["Country_Egypt"] },
      { "name": "Fire_Platform_(Country_Egypt)", "enabled": true, "category": ["Country_Egypt"] },
      { "name": "Obelisk_(Country_Egypt)", "enabled": true, "category": ["Country_Egypt"] },
      { "name": "Wall_(Country_Egypt)", "enabled": true, "category": ["Country_Egypt"] },
  
      { "name": "Wall_(Country_France)", "enabled": true, "category": ["Country_France"] },
      { "name": "Street_Light_(Country_France)", "enabled": true, "category": ["Country_France"] },
      { "name": "Plate_(Country_France)", "enabled": true, "category": ["Country_France"] },
      { "name": "Picnic_Carpet_(Country_France)", "enabled": true, "category": ["Country_France"] },
      { "name": "Picnic_Backet_Cover_(Country_France)", "enabled": true, "category": ["Country_France"] },
      { "name": "Picnic_Backet_(Country_France)", "enabled": true, "category": ["Country_France"] },
      { "name": "Hot_Dog_(Country_France)", "enabled": true, "category": ["Country_France"] },
      { "name": "Hot_Air_Balloon_(Country_France)", "enabled": true, "category": ["Country_France"] },
      { "name": "Eiffle_Tower_(Country_France)", "enabled": true, "category": ["Country_France"] },
      { "name": "Cup_(Country_France)", "enabled": true, "category": ["Country_France"] },
      { "name": "Bottle_(Country_France)", "enabled": true, "category": ["Country_France"] },
      { "name": "Bicycle_(Country_France)", "enabled": true, "category": ["Country_France"] },
  
      { "name": "Bridge_(Country_Japan)", "enabled": true, "category": ["Country_Japan"] },
      { "name": "Light_Stand_(Country_Japan)", "enabled": true, "category": ["Country_Japan"] },
      { "name": "Painting_(Country_Japan)", "enabled": true, "category": ["Country_Japan"] },
      { "name": "Plant_(Country_Japan)", "enabled": true, "category": ["Country_Japan"] },
      { "name": "Round_Window_(Country_Japan)", "enabled": true, "category": ["Country_Japan"] },
      { "name": "Toril_(Country_Japan)", "enabled": true, "category": ["Country_Japan"] },
      { "name": "Wall_(Country_Japan)", "enabled": true, "category": ["Country_Japan"] },
      { "name": "Wealth_Cat_(Country_Japan)", "enabled": true, "category": ["Country_Japan"] },
      { "name": "Window_(Country_Japan)", "enabled": true, "category": ["Country_Japan"] },
  
      { "name": "Camp_Fire_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Candle_Stick_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Carpet_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Christmas_Ring_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Christmas_Tree_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Gift_Cube_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Gift_Cuboid_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Lamp_Line_A_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Lamp_Line_B_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Rocking_Chair_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Shelf_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Stove_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Tool_A_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Tool_B_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
      { "name": "Wall_(Festival_Christmas)", "enabled": true, "category": ["Festival_Christmas"] },
  
      { "name": "Candle_A_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Candle_B_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Candle_C_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Cloud_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "House_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Monster_Foot_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Monster_Hand_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Moon_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Posion_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Pumkin_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Railing_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Skull_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Spider_Web_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Tombstone_A_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Tombstone_B_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Tombstone_C_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Tombstone_D_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Tree_(Festival_Halloween)", "enabled": true, "category": ["Festival_Halloween"] },
      { "name": "Wall_(Festival_Halloween)", "enabled": "false No Image", "category": ["Festival_Halloween"] },
  
      { "name": "Bottle_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Box_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Coffee_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Cutboard_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Fridge_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Island_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Oven_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Pot_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Shelf_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Sink_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Table_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Towel_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Trolley_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Wall_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
      { "name": "Window_(Hobbies_Cooking)", "enabled": true, "category": ["Hobbies_Cooking"] },
  
      { "name": "Bed_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Carpet_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Court_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Foot_Ball_A_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Foot_Ball_B_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Foot_Ball_C_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Foot_Ball_D_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Foot_Ball_Stand_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Goal_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Lamp_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Small_Goal_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Sofa_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "TV_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "Wall_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
      { "name": "World_Cup_(Hobbies_FootBall)", "enabled": true, "category": ["Hobbies_FootBall"] },
  
      { "name": "Cabinet_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Figure_Amoug_Us_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Game_Box_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Game_Chair_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "KeyBoard_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Light_Pad_Hexagon_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Light_Pad_Triangle_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Mac_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Mouse_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Photo_Frame_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "PS_Lamp_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Screen_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Table_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "TV_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Wall_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
      { "name": "Wifi_Router_(Hobbies_Gaming)", "enabled": true, "category": ["Hobbies_Gaming"] },
  
      { "name": "Bench_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "Chair_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "Door_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "Fence_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "Frame_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "Garlamd_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "Light_Bulb_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "MailBox_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "PlantA_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "PlantB_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "Props_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "Table_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
      { "name": "Wall_(Hobbies_Garden)", "enabled": true, "category": ["Hobbies_Garden"] },
  
      { "name": "Bracket_(Hobbies_Sport)", "enabled": true, "category": ["Hobbies_Sport"] },
      { "name": "Discus_(Hobbies_Sport)", "enabled": true, "category": ["Hobbies_Sport"] },
      { "name": "Discus_Holder_(Hobbies_Sport)", "enabled": true, "category": ["Hobbies_Sport"] },
      { "name": "Dumbell_(Hobbies_Sport)", "enabled": true, "category": ["Hobbies_Sport"] },
      { "name": "Gloves_(Hobbies_Sport)", "enabled": true, "category": ["Hobbies_Sport"] },
      { "name": "Kettle_Bell_(Hobbies_Sport)", "enabled": true, "category": ["Hobbies_Sport"] },
      { "name": "Sand_Bag_(Hobbies_Sport)", "enabled": true, "category": ["Hobbies_Sport"] },
      { "name": "Wall_(Hobbies_Sport)", "enabled": true, "category": ["Hobbies_Sport"] },
      { "name": "Word_Light_(Hobbies_Sport)", "enabled": true, "category": ["Hobbies_Sport"] },
  
      { "name": "Book_A_(Name_Veuns)", "enabled": true, "category": ["Name_Veuns"] },
      { "name": "Book_B_(Name_Veuns)", "enabled": true, "category": ["Name_Veuns"] },
      { "name": "Book_C_(Name_Veuns)", "enabled": true, "category": ["Name_Veuns"] },
      { "name": "Book_Shelf_(Name_Veuns)", "enabled": true, "category": ["Name_Veuns"] },
      { "name": "Carpet_(Name_Veuns)", "enabled": true, "category": ["Name_Veuns"] },
      { "name": "Chair_(Name_Veuns)", "enabled": true, "category": ["Name_Veuns"] },
      { "name": "Computer_(Name_Veuns)", "enabled": true, "category": ["Name_Veuns"] },
      { "name": "Desk_(Name_Veuns)", "enabled": true, "category": ["Name_Veuns"] },
      { "name": "Draw_Desk_(Name_Veuns)", "enabled": true, "category": ["Name_Veuns"] },
      { "name": "Earth_(Name_Veuns)", "enabled": true, "category": ["Name_Veuns"] },
      { "name": "Wall_(Name_Veuns)", "enabled": true, "category": ["Name_Veuns"] },
  
      { "name": "Book_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Book_Shelf_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Cabinet_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Carpet_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Cat_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Cushion_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Diving_Photo_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Figure_Canada_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Figure_Hong_Kong_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Figure_Japan_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Figure_USA_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Pet_Food_Plate_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Plastic_Plate_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Sofa_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Sound_Bar_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "TV_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Wall_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
      { "name": "Word_(Name_VeunsB)", "enabled": true, "category": ["Name_VeunsB"] },
  
      { "name": "Beach_Chair_(Seasons_Summer)", "enabled": true, "category": ["Seasons_Summer"] },
      { "name": "Bench_(Seasons_Summer)", "enabled": true, "category": ["Seasons_Summer"] },
      { "name": "Bucket_(Seasons_Summer)", "enabled": true, "category": ["Seasons_Summer"] },
      { "name": "Poor_Ring_A_(Seasons_Summer)", "enabled": true, "category": ["Seasons_Summer"] },
      { "name": "Poor_Ring_B_(Seasons_Summer)", "enabled": true, "category": ["Seasons_Summer"] },
      { "name": "Surboard_(Seasons_Summer)", "enabled": true, "category": ["Seasons_Summer"] },
      { "name": "Table_(Seasons_Summer)", "enabled": true, "category": ["Seasons_Summer"] },
      { "name": "Umbrella_(Seasons_Summer)", "enabled": true, "category": ["Seasons_Summer"] },
      { "name": "Wall_(Seasons_Summer)", "enabled": true, "category": ["Seasons_Summer"] },
      { "name": "Watermelon_(Seasons_Summer)", "enabled": true, "category": ["Seasons_Summer"] },
  
      { "name": "Bakery_Word_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Basket_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_A_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_A_Half_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_B_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_B_Half_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_C_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_D_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_E_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_F_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_G_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_H_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_I_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Bread_I_OnePiece_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Cabinet_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Counter_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Cream_Croissant_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Croissant_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Cutting_Board_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Knife_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Pie_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Table_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Wall_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Wooden_Box_A_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Wooden_Box_B_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Wooden_Box_C_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
      { "name": "Wooden_Table_(Shop_Bakery)", "enabled": true, "category": ["Shop_Bakery"] },
  
      { "name": "Album_(Theme_Band)", "enabled": true, "category": ["Theme_Band"] },
      { "name": "AMP_(Theme_Band)", "enabled": true, "category": ["Theme_Band"] },
      { "name": "Drump_(Theme_Band)", "enabled": true, "category": ["Theme_Band"] },
      { "name": "GuiltarA_(Theme_Band)", "enabled": true, "category": ["Theme_Band"] },
      { "name": "GuiltarB_(Theme_Band)", "enabled": true, "category": ["Theme_Band"] },
      { "name": "Light_Box_(Theme_Band)", "enabled": true, "category": ["Theme_Band"] },
      { "name": "Wall_(Theme_Band)", "enabled": true, "category": ["Theme_Band"] },
  
      { "name": "Boiling_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Book_A_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Book_B_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Book_C_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Book_Shelf_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Broom_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Candle_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Carpet_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Color_Window_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Crystal_Ball_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Flag_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Fly_Book_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Magician_Stuff_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Mirror_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Table_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Wall_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
      { "name": "Wall_(Theme_Magic)", "enabled": true, "category": ["Theme_Magic"] },
  
      { "name": "Bottle_(Theme_Nautical)", "enabled": true, "category": ["Theme_Nautical"] },
      { "name": "Cushion_(Theme_Nautical)", "enabled": true, "category": ["Theme_Nautical"] },
      { "name": "Flag_(Theme_Nautical)", "enabled": true, "category": ["Theme_Nautical"] },
      { "name": "Map_(Theme_Nautical)", "enabled": true, "category": ["Theme_Nautical"] },
      { "name": "Mark_(Theme_Nautical)", "enabled": true, "category": ["Theme_Nautical"] },
      { "name": "Pool_Ring_(Theme_Nautical)", "enabled": true, "category": ["Theme_Nautical"] },
      { "name": "Round_Window_(Theme_Nautical)", "enabled": true, "category": ["Theme_Nautical"] },
      { "name": "Ship_Bed_(Theme_Nautical)", "enabled": true, "category": ["Theme_Nautical"] },
      { "name": "Treasure_Box_(Theme_Nautical)", "enabled": true, "category": ["Theme_Nautical"] },
      { "name": "Wall_(Theme_Nautical)", "enabled": true, "category": ["Theme_Nautical"] },
      { "name": "Wheel_(Theme_Nautical)", "enabled": true, "category": ["Theme_Nautical"] },
  
      { "name": "Balloon_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "Bottle_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "Cake_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "CupCake_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "Flag_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "Gift_A_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "Gift_B_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "Gift_C_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "Glass_cup_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "Party_Balloon_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "Rocking_Horse_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "Table_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
      { "name": "Wall_(Theme_Party)", "enabled": true, "category": ["Theme_Party"] },
  
      { "name": "Gate_A_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
      { "name": "Gate_B_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
      { "name": "Gate_C_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
      { "name": "Ground_A_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
      { "name": "Ground_B_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
      { "name": "Ground_C_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
      { "name": "Pillar_A_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
      { "name": "Pillar_B_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
      { "name": "Props_A_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
      { "name": "Sill_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
      { "name": "Wall_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
      { "name": "Wall_A_(Theme_SciFi)", "enabled": true, "category": ["Theme_SciFi"] },
  
      { "name": "Tie_Fighter_(Theme_StarWar)", "enabled": true, "category": ["Theme_StarWar"] },
      { "name": "Wall_(Theme_StarWar)", "enabled": true, "category": ["Theme_StarWar"] },
  
      { "name": "Brick_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Carpet_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Cloth_A_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Flower_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Pillar_A_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Pillar_B_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Pillar_C_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Pillar_D_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Pillar_E_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Platform_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Podium_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Standed_Glass_A_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Standed_Glass_B_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Vase_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Wall_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] },
      { "name": "Wood_Chair_(Theme_Wedding)", "enabled": true, "category": ["Theme_Wedding"] }
    ]
  }
  